apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsentinel

resources:
  - ../../../base

patches:
  - target:
      kind: Deployment
      name: ngrok
    path: deployment-ngrok.patch.yaml
  - target:
      kind: Route
      name: netsentinel-route
    path: app-route.patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: ocpclient-clusterrolebinding
    path: clusterrolebinding.patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: cluster-monitoring-view-binding
    path: cluster-monitoring-view-binding.patch.yaml
  - target:
      kind: SecurityContextConstraints
      name: netsentinel-privileged-scc
    path: custom-scc.patch.yaml

secretGenerator:
  - name: ngrok-token
    literals:
      - NGROK_AUTHTOKEN=2m7FVIePrGO5njNAXC5Wy4c40f2_5pv58J8wbsgjYV7WHZW6T
    type: Opaque
    behavior: replace

configMapGenerator:
  - name: app-config
    files:
      - config.yaml=app-config.yaml
    behavior: replace
