apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsentinel

resources:
  - ./serviceaccounts/app-serviceaccount.yaml
  - ./deployments/app-deployment-kafkacred.yaml
  - ./deployments/ngrok-deployment.yaml
  - ./services/app-service.yaml
  - ./routes/app-route.yaml
  - ./secrets/ngrok-token-secret.yaml
  - ./configmaps/app-configmap.yaml
  - ./rbac/clusterrole.yaml
  - ./rbac/clusterrolebinding.yaml
  - ./rbac/custom-scc.yaml
  - ./rbac/cluster-monitoring-view-binding.yaml

secretGenerator:
  - name: ngrok-token
    literals:
      - NGROK_AUTHTOKEN=2m7FVIePrGO5njNAXC5Wy4c40f2_5pv58J8wbsgjYV7WHZW6T
    type: Opaque
    behavior: replace

configMapGenerator:
  - name: app-config
    files:
      - config.yaml=app-config.yaml
    behavior: replace

patches: []

generatorOptions:
  disableNameSuffixHash: true
