# config.yaml

num_train_epochs: 0.1
learning_rate: 5e-5
per_device_train_batch_size: 4
logging_steps: 100
save_strategy: steps
save_steps: 100
log_level: DEBUG
use_gpu: true
gradient_accumulation_steps: 1
max_length: 512
early_stopping: true
early_stopping_patience: 2
evaluation_strategy: steps
eval_steps: 500
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
subset_size: 100
