version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "conn:1:1,http:1:1,dns:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zeek:
    build:
      context: ./zeek
      dockerfile: Dockerfile
    container_name: zeek
    depends_on:
      - kafka
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./zeek_scripts:/usr/local/zeek_scripts
      - ./zeek-config/node.cfg:/opt/zeek/etc/node.cfg
      - ./zeek-config/zeekctl.cfg:/opt/zeek/etc/zeekctl.cfg
      - ./zeek-config/local.zeek:/opt/zeek/share/zeek/site/local.zeek
    command: ["/opt/zeek/bin/zeekctl", "deploy"]
    environment:
      LD_LIBRARY_PATH: "/opt/zeek/lib"

  # Optional: Kafka UI for monitoring
  kafkaui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
