apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsentinel

resources:
  - ../../base

images:
  - name: quay.io/bpandey/netsentenial
    newTag: 0.0.5-torch-cpu

patches:
  - target:
      kind: Deployment
      name: ngrok
    path: deployment-ngrok.patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: ocpclient-clusterrolebinding
    path: clusterrolebinding.patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: cluster-monitoring-view-binding
    path: cluster-monitoring-view-binding.patch.yaml
  - target:
      kind: SecurityContextConstraints
      name: netsentinel-privileged-scc
    path: custom-scc.patch.yaml

  - target:
      kind: Deployment
      name: netsentinel
    path: deployment-sleep-infinity.patch.yaml

secretGenerator:
  - name: ngrok-token
    literals:
      - NGROK_AUTHTOKEN=2gvfdllTZLwjXrKRPGWHGcB5mSt_48N254h3EgdxfFjhziJh9
    type: Opaque
    behavior: replace

configMapGenerator:
  - name: app-config
    files:
      - config.yaml=app-config.yaml
    behavior: replace



namePrefix: telcolab-
