apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsentinel

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: ngrok
    path: deployment-ngrok.patch.yaml

  # - target:
  #     kind: Deployment
  #     name: netsentenial
  #   path: deployment-sleep-infinity.patch.yaml

secretGenerator:
  - name: ngrok-token
    literals:
      - NGROK_AUTHTOKEN=2gvfdllTZLwjXrKRPGWHGcB5mSt_48N254h3EgdxfFjhziJh9
    type: Opaque
    behavior: replace

configMapGenerator:
  - name: app-config
    files:
      - config.yaml=app-config.yaml
    behavior: replace

images:
  - name: quay.io/bpandey/netsentenial
    newTag: 0.0.5-torch-cpu

namePrefix: telcolab-
