apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: netsentenial
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
