apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocpclient-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: netsentenial-sa
    namespace: netsentenial
roleRef:
  kind: ClusterRole
  name: ocpclient-clusterrole
  apiGroup: rbac.authorization.k8s.io
