apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: container-build-and-push
spec:
  params:
    - default: "quay.io/bpandey/netsentinel:latest"
      name: IMAGE_NAME
      type: string
    - default: "git@github.com:pandeybk/NetSentenial.git"
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
  workspaces:
    - name: workspace
    - name: quay-credentials

  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace

    - name: kaniko
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: DOCKERFILE
          value: ./Dockerfile.multistage
        - name: CONTEXT
          value: ./
        - name: EXTRA_ARGS
          value: []
        - name: BUILDER_IMAGE
          value: gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: kaniko
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: quay-credentials
