api_config:
  host: "0.0.0.0"
  port: 5000
  debug: true

model_config:
  # predictive_model_path: "models/predictive_model/model.joblib"
  llm_model_path: "models/llm_model"
  embedding_model_name: "all-MiniLM-L6-v2"
  predictive_model_path: "models/predictive_model/model.onnx"

slack_config:
  slack_channel: "#netsentenial"
  # slack_bot_token: "xoxb-your-slack-bot-token"
  # slack_signing_secret: "your-slack-signing-secret"
  
kafka:
  bootstrap: netsentenial-kafka-kafka-bootstrap.openshift-operators:9092

