# config/attack-config.yml

fuzzers:
  target_url: "http://192.168.156.103:32061/login.php"
  wordlist: "/usr/share/wfuzz/wordlists/general/common.txt"

analysis:
  target_ip: "192.168.156.103"
  target_port: 443

backdoors:
  lhost: "192.168.156.110"
  lport: 4444

dos:
  target_ip: "192.168.156.103"
  target_port: 80
  method: "GET"
  threads: 100

exploits:
  target_ip: "192.168.156.103"
  payload: "windows/meterpreter/reverse_tcp"
  lhost: "192.168.156.110"
  lport: 4444

generic:
  target_ip: "192.168.156.103"
  target_port: 80

reconnaissance:
  target_network: "192.168.1.0/24"

shellcode:
  lhost: "192.168.156.110"
  lport: 4444

worms:
  target_ip: "192.168.156.103"
  target_port: 4444

brute_force:
  target_service: "ssh://192.168.156.103:22"
  username: "admin"
  password_file: "/usr/share/wordlists/rockyou.txt"
