apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netsentinel
  template:
    metadata:
      labels:
        app: netsentinel
    spec:
      serviceAccountName: netsentinel-sa
      containers:
        - name: netsentinel
          image: quay.io/bpandey/netsentinel:0.0.5-torch-cpu-with-models
          command: ["sh", "-c", "python app/run.py"]
          ports:
            - containerPort: 5000
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          env:
            - name: KAFKA_USERNAME
              value: "netsentinel-kafka-user"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netsentinel-kafka-user
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "console-kafka-kafka-secure-bootstrap:9093" # This override not working yet, use app config for now
          volumeMounts:
            - name: data-volume
              mountPath: /app/vectordata
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: console-kafka-cluster-ca-cert
              mountPath: /usr/local/share/ca-certificates/
              readOnly: true

        - name: create-mock-data
          image: quay.io/bpandey/netsentinel:0.0.5-torch-cpu-with-models
          command: ["sh", "-c", "python scripts/create_mock_data.py"]
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          env:
            - name: KAFKA_USERNAME
              value: "netsentinel-kafka-user"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netsentinel-kafka-user
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "console-kafka-kafka-secure-bootstrap:9093" # This override not working yet, use app config for now
          volumeMounts:
            - name: data-volume
              mountPath: /app/vectordata
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: console-kafka-cluster-ca-cert
              mountPath: /usr/local/share/ca-certificates/
              readOnly: true

        - name: process-mock-data
          image: quay.io/bpandey/netsentinel:0.0.5-torch-cpu-with-models
          command: ["sh", "-c", "python scripts/process_mock_data.py"]
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          env:
            - name: KAFKA_USERNAME
              value: "netsentinel-kafka-user"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netsentinel-kafka-user
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "console-kafka-kafka-secure-bootstrap:9093" # This override not working yet, use app config for now
          volumeMounts:
            - name: data-volume
              mountPath: /app/vectordata
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: console-kafka-cluster-ca-cert
              mountPath: /usr/local/share/ca-certificates/
              readOnly: true

        - name: prediction-service
          image: quay.io/bpandey/netsentinel:0.0.5-torch-cpu-with-models
          command: ["sh", "-c", "python scripts/prediction_service.py"]
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          env:
            - name: KAFKA_USERNAME
              value: "netsentinel-kafka-user"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netsentinel-kafka-user
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "console-kafka-kafka-secure-bootstrap:9093" # This override not working yet, use app config for now
          volumeMounts:
            - name: data-volume
              mountPath: /app/vectordata
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: console-kafka-cluster-ca-cert
              mountPath: /usr/local/share/ca-certificates/
              readOnly: true

      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config-volume
          configMap:
            name: app-config
        - name: console-kafka-cluster-ca-cert
          secret:
            secretName: console-kafka-cluster-ca-cert
