apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsentenial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netsentenial
  template:
    metadata:
      labels:
        app: netsentenial
    spec:
      serviceAccountName: netsentenial-sa
      containers:
        - name: netsentenial
          image: quay.io/bpandey/netsentenial:0.0.1
          command: ["sh", "-c", "python app/run.py"]
          ports:
            - containerPort: 5000
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
            - name: data-volume
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml

        - name: create-mock-data
          image: quay.io/bpandey/netsentenial:0.0.1
          command: ["sh", "-c", "python scripts/create_mock_data.py"]
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
            - name: data-volume
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml

        - name: process-mock-data
          image: quay.io/bpandey/netsentenial:0.0.1
          command: ["sh", "-c", "python scripts/process_mock_data.py"]
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
            - name: data-volume
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml

        - name: prediction-service
          image: quay.io/bpandey/netsentenial:0.0.1
          command: ["sh", "-c", "python scripts/prediction_service.py"]
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonGroup: 0
            runAsUser: 0
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
            - name: data-volume
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml

      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: models-pvc
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config-volume
          configMap:
            name: app-config
