apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: netsentenial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: wernight/ngrok
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-token
                  key: NGROK_AUTHTOKEN
          command: ["ngrok"]
          args: ["http", "--log=stdout", "app-service:5000"]
          ports:
            - name: http
              containerPort: 4040
