apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limits
  namespace: your-namespace
spec:
  limits:
    - type: Container
      default:
        ephemeral-storage: "100Gi"
      defaultRequest:
        ephemeral-storage: "10Gi"
